project:
  type: website

website:
  title: "My Blog Attempts: David Arroyo"
  navbar:
    right:
      - about.qmd
    
format:
  html:
    theme: vapor
    css: styles.css

execute:
  freeze: auto


